version: '3.8'

services:
  db:
    image: postgres:15
    container_name: movein_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moveindb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: movein_web
    restart: always
    ports:
      - "3001:8000"
    depends_on:
      - db

volumes:
  postgres_data: